### ISSUE TITLE
[HELP] Hit ratio?

### ISSUE THREAD

**Issue by karthikraja95** [amoussawi/recoder#2]
Hi @amoussawi 
Is there any function in the repo to calculate the hit ratio? 

Hit Ratio at N, or HR@n, a way of calculating how many "hits" you have in an n-sized list of ranked items (here the top 10 recommendations). A "hit" could be defined as something that the user has purchased.

**Comment by amoussawi** [comment]
If Hit ratio has the same definition as Recall, then you have it in `recoder.metrics.Recall`, but if it has the same definition as Precision, then it's not there. But you can implement any metric you want by implementing this interface `recoder.metrics.Metric`, you can look at how the Recall is implemented as an example.

**Comment by amoussawi** [comment]
Closing. Feel free to reopen if you still have any question.
