### ISSUE TITLE
[HELP] How to use Similarity Recommender from recoder

### ISSUE THREAD

**Issue by karthikraja95** [amoussawi/recoder#4]
Hi @amoussawi 
I am trying to recommend something with Similarity Recommender.

I want to use num_recommendations = 10

What do I need to pass for embedding index? 

I looked into recoder.embedding.EmbeddingsIndex. Do I need to use AnnoyEmbeddingIndex? If so, how?  Am I missing something? Any help would be appreciated

**Comment by amoussawi** [comment]
I don't think there's a need to use because it's not well implemented and there's no benefit from it. it was just experimental.  it will get removed in later releases.
