### ISSUE TITLE
[HELP] Prediction on a particular item for a selected user

### ISSUE THREAD

**Issue by karthikraja95** [amoussawi/recoder#5]
Hi all,

I am new to recommender systems; I used Dynamic Autoencoder from recoder code base for my recommendations. My question is, let's say I want to predict the value of a particular item for a selected user.

For example:
UserID - 4307
ItemID - 9024
Ground_truth - 1.0
Prediction_Output - ?

How do I find the prediction score for the above problem? Is there any inbuilt function available in recoder in doing that? If not, can you suggest a way to do that?

Thanks

**Comment by amoussawi** [comment]
You can use `Recoder.predict`, but you have to put your input in a `UsersInteractions` object.

**Comment by karthikraja95** [comment]
Ok, How do I pass both userID and itemID as an input to UserInteractions object, I know I can pass userID and csr matrix in UserInteractions object but how do I pass userID and itemID? 

I just want to find the prediction for a selected userID (1001) and a selected itemID (1234) ?

**Comment by karthikraja95** [comment]
Hi @amoussawi 

recoder.predict(UserInteractions) - Predicts the user interactions with all items

I want to know if there is any way I can able to predict the output for a single user with a single item?

is there a way in this repo? or any other ideas to implement that?

Thanks

**Comment by amoussawi** [comment]
> recoder.predict(UserInteractions) - Predicts the user interactions with all items

you can predict interactions with all items and then use the item_id_map in recoder object to index the item you want to predict for
